//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by tuc.rc
//
#define IDC_ABOUT                       3
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_TUC_DIALOG                  102
#define CG_IDS_SOCKETS_INIT_FAILED      103
#define IDR_MAINFRAME                   128
#define IDC_SENDINFO                    1000
#define IDC_MYIPADDR                    1001
#define IDC_HOSTADDR                    1003
#define IDC_SYS1                        1004
#define IDC_RECINFO                     1005
#define IDC_ALL                         1006
#define IDC_PEER                        1007
#define IDC_HOSTNAME                    1008
#define IDC_SYS2                        1009
#define IDC_NET                         1010
#define IDC_NET0                        1011
#define IDC_NET1                        1012
#define IDC_NET2                        1013
#define IDC_NET3                        1014
#define IDC_GETHOT                      1015
// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1016
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
